version: '3.7'
services:
    dbhost:
        image: mongo:4.0.2-xenial
        restart: always
        container_name: dbhost
        volumes:
            - $HOME/backup:/warehouse
            - $HOME/data/db:/data/db
        ports:
            - "27018:27017"
        command: mongod --logpath=/dev/null
    eunews:
        image: artgoldhammer/nooze:$NZTAG
        container_name: eunews
        restart: always
        volumes:
            - $HOME/Prog/nooze/confs:/app/confs
        environment:
            NZDBCONF: /app/confs/elite-eu-dkr.conf
        ports:
            - "9091:9090"
            - "3032:3031"

    usnews:
        image: artgoldhammer/nooze:$NZTAG
        container_name: usnews
        restart: always
        volumes:
            - $HOME/Prog/nooze/confs:/app/confs
        environment:
            NZDBCONF: /app/confs/elite-us-dkr.conf
        ports:
            - "9090:9090"
            - "3031:3031"
 
